
###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json
Origin: http://localhost:8080

{
    "username": "john.doe@example.com",
    "password": "Password123!"
}



###
@id = 1

GET http://localhost:8080/api/v1/partner/{{id}}
X-Api:"12312313190381203"

###
OPTIONS http://localhost:8080/api/v1/auth/login
Content-Type: application/json
Origin: http://localhost:3000
Accept: */*
Access-Control-Request-Headers: content-type, authorization
Access-Control-Request-Method: POST
Authorization: Bearer 123

{
  "username": "john.doe@example.com",
  "password": "Password123!"
}


